### ISSUE TITLE
delay() is not working as expected

### ISSUE THREAD

**Issue by dragan1alex** [damellis/attiny#100]
the delay(ms) function is not working at all as expected on the 1mhz and 8mhz internal clocks(the ones I tested). It seems to delay ten times more than it's supposed to, I haven't measured it exactly.

**Comment by dragan1alex** [comment]
nevermind, I'm an idiot, I was trying to set a value of 47000 or something in an int variable, keep up the awesome work guys :D

**Comment by damellis** [comment]
Glad it's working! Thanks for the updates...
