### ISSUE TITLE
mising spi.h?

### ISSUE THREAD

**Issue by budaics** [damellis/attiny#113]
C:\Users\user\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.16\libraries\SPI\src/SPI.h:310:55: error: 'SPIE' was not declared in this scope

   inline static void detachInterrupt() { SPCR &= ~_BV(SPIE); }

                                                       ^

exit status 1
Error compiling for board ATtiny25/45/85.
![image](https://cloud.githubusercontent.com/assets/6849527/21490364/f9eb1314-cbf3-11e6-8715-7ca0c9bc79f5.png)

**Comment by damellis** [comment]
Unfortunately, the ATtiny25/45/85 doesn't support SPI.
