### ISSUE TITLE
delayMicroseconds() only correct @ 8MHz (ATtiny85)

### ISSUE THREAD

**Issue by erniberni** [damellis/attiny#12]
Hi, 
I just found out that delayMicroseconds() produces only at 8 MHz clock correct values. When flashing the same code on an ATtiny85 with 1 MHz the us-delay is factor 8 too long. The function of delay() is in both cases correct.
Regards
Reinhard

**Comment by DaniDD** [comment]
No, not from core, you forgot to set the correct fuse byte in avrdude.
You must set it to 0x62 for 1MHz and 0xe2 for 8MHz

**Comment by damellis** [comment]
This has since been fixed in the Arduino core and delayMicroseconds() appears to work correctly at 1 MHz w/ Arduino 1.6.7 (AVR core 1.6.9) and possibly earlier: https://github.com/arduino/Arduino/pull/1678
