### ISSUE TITLE
Attiny 1.5 support

### ISSUE THREAD

**Issue by ira-hart** [damellis/attiny#49]
I cant get Arduino IDE 1.5 to work for Attiny.  If I use your latest release: attiny-ide-1.5.x, and I put the attiny dir in the hardware dir, I see Attiny as a board choice.  
It does not say Attiny85, Attiny45 etc.  It does compile.

**Comment by consolacion** [comment]
Your core works fine. Thanks. I use the Smeezekitty core for Attiny13 but I read somewhere that your core would also support attiny13 'if a few' configurations added' (!)
Can you confirm that?
Would  those configurations only be an addition in the boards.txt?  Or is something else necessary (if possible at all)
