### ISSUE TITLE
Working on Arduino Nano v3?

### ISSUE THREAD

**Issue by lost-hope** [damellis/attiny#51]
Hello,
I know that this toutorial ist some days old, but I found an ATtiny44a. So now i want to program this chip. Can I use my Arduino Nano or does only the Uno and Duemilanove? They use the same main chip ( ATmega328).

I am looking forward to get an answer from you

**Comment by damellis** [comment]
Not sure if this is still useful, but it sounds like the Nano couldn't talk to the ATtiny. Check the wiring, that the ATtiny is getting power, etc.

**Comment by damellis** [comment]
Closing this because (AFAICT) there's nothing to fix within the ATtiny files. Let me know if you have other questions.
