### ISSUE TITLE
Can't compile if binary > ~4.5KB on ATTiny84

### ISSUE THREAD

**Issue by ghost** [damellis/attiny#7]
I get the following error when I try to compile anything bigger than ~4.5KB:

arduino-1.0.1/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr25/crttn84.o:(.init9+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `exit' defined in .fini9 section in arduino1.0.1/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/avr25\libgcc.a(_exit.o)

**Comment by damellis** [comment]
I believe this fix has since been incorporated into the Arduino software / AVR core, so I'm closing this. Please re-open if it's still an issue.
