### ISSUE TITLE
Will not compile some libs due to missing definition of __AVR_ATtinyX5__

### ISSUE THREAD

**Issue by VaclavSynacek** [damellis/attiny#72]
Manchester library (and maybe others too) will not compile for ATtiny85 due to due to missing definition of `__AVR_ATtinyX5__` . See http://arduino.stackexchange.com/a/1306 for more datails.

**Comment by olvap** [comment]
any news on this?

**Comment by lezhanger** [comment]
H, perhaps try this: https://github.com/mchr3k/arduino-libs-manchester/issues/13
I changed from AVR_ATtinyX5 should become AVR_ATtiny85 in the Manchester.cpp file and ATtiny85 now compiles.

**Comment by psbs** [comment]
thanks a lot. it does compile on replacing  AVR_ATtinyX5 with AVR_ATtiny85  in the Manchester.cpp file

**Comment by VaclavSynacek** [comment]
I do not need this any more and others seem happy with the workaround discussed => closing this 4 year old issue.
