### ISSUE TITLE
arduino 1.6.6 board manager

### ISSUE THREAD

**Issue by piobel** [damellis/attiny#78]
the json link don't work on board manager arduino 1.6.6

**Comment by per1234** [comment]
I just tested it with Arduino IDE 1.6.6 2015/08/20 05:41 and it worked for me. Could you try again and give more information on what doesn't work please. If you have multiple Additional Boards Manager URLs in your preferences post the whole list.

**Comment by piobel** [comment]
Il giorno 20/ago/2015, alle ore 22:48, per1234 <notifications@github.com> ha scritto:

I just tested it with Arduino IDE 1.6.6 2015/08/20 05:41 and it worked for me. Could you try again and give more information on what doesn't work please. If you have multiple Additional Boards Manager URLs in your preferences post the whole list.

**Comment by per1234** [comment]
@piobel did you try to post some information as an attachment to the email? That doesn't work.

**Comment by piobel** [comment]
please did you see the PNG attached ?


Il giorno 21/ago/2015, alle ore 12:16, per1234 <notifications@github.com> ha scritto:

@piobel did you try to post some information as an attachment to the email? That doesn't work.

**Comment by piobel** [comment]
HI,

reinstall IDE 1..6.5  an this is new error in board manager




Il giorno 20/ago/2015, alle ore 22:48, per1234 <notifications@github.com> ha scritto:

I just tested it with Arduino IDE 1.6.6 2015/08/20 05:41 and it worked for me. Could you try again and give more information on what doesn't work please. If you have multiple Additional Boards Manager URLs in your preferences post the whole list.

**Comment by per1234** [comment]
>please did you see the PNG attached ?

As I said before, **email attachments don't work on GitHub**. You need to either attach the image to a message on GitHub or type the error out in email.

**Comment by damellis** [comment]
Not sure what's going on here so I'm closing this. If you continue to have problems, please re-open or create a new issue.
