### ISSUE TITLE
Update json for ATtiny2x

### ISSUE THREAD

**Issue by purewell** [damellis/attiny#94]
Last master json is 10 months ago. It's not supports ATtiny2x series.
But last master branche works on ATtiny24 very well. :+1: 
Plz, update json and package zip file for ATtiny24.

**Comment by per1234** [comment]
@damellis I'd be happy to update the JSON file if you want. I'm not sure what the new version should be, 1.1.1?

**Comment by purewell** [comment]
I agree that 1.1.1. :)

**Comment by damellis** [comment]
Sure, sounds good.

**Comment by damellis** [comment]
Fixed by https://github.com/damellis/attiny/commit/9df3a3d19d12fe103924afb246bbf7d7cd0d40ed
